services:
  # Web Sayt - Static Site
  - type: web
    name: mahsulot-admin-panel
    env: static
    buildCommand: echo "Static site - no build needed"
    staticPublishPath: ./web
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_ENV
        value: production

  # Telegram Bot - Background Worker
  - type: worker
    name: mahsulot-telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python telegram_bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
    autoDeploy: true
